### ISSUE TITLE
editor truncates the text at 250 000 bytes

### ISSUE THREAD

**Issue by mtrevisan** [mafgwo/stackedit-plus#16]
I see there's a byte limit in the editor, which is 250 000 bytes, after which the text is truncated. Is it possible to remove this limitation?
Thank you

**Comment by mafgwo** [comment]
StackEdit doesn't impose this kind of limitation. This restriction is caused by third-party repositories. If your workspace is of the Gitea type, there should be no such limitation.

**Comment by mtrevisan** [comment]
Thank you.
